// AUTO-GENERATED by .shared/codegen/csharp_gen.py - do not edit by hand
//
// These POCOs enforce SHAPE only. Constraints declared in the JSON
// schemas (schema_version const, numeric ranges, enums, minLength, etc.)
// are NOT enforced by these classes. Per spec §7, every cross-module
// payload must be validated against the corresponding schema in
// C:/Dev/.shared/schemas/ at the boundary (use a JSON Schema validator
// such as NJsonSchema or Json.NET Schema before consuming the payload).
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace ForeverEngine.Bridges
{
    // from action.schema.json
    [Serializable]
    public class ActionRequest
    {
        [JsonProperty("schema_version")] public string SchemaVersion;
        [JsonProperty("session_id")] public string SessionId;
        [JsonProperty("actor_id")] public string ActorId;
        [JsonProperty("target_id")] public string TargetId;
        [JsonProperty("player_input")] public string PlayerInput;
        [JsonProperty("actor_stats")] public Dictionary<string, object> ActorStats;
        [JsonProperty("target_stats")] public Dictionary<string, object> TargetStats;
        [JsonProperty("scene_context")] public Dictionary<string, object> SceneContext;
        [JsonProperty("recent_history")] public List<string> RecentHistory;
    }

    // from decision.schema.json
    [Serializable]
    public class DecisionPayload
    {
        [JsonProperty("schema_version")] public string SchemaVersion;
        [JsonProperty("session_id")] public string SessionId;
        [JsonProperty("success")] public bool Success;
        [JsonProperty("scale")] public int Scale;
        [JsonProperty("narrative_text")] public string NarrativeText;
        [JsonProperty("stat_effects")] public List<Dictionary<string, object>> StatEffects;
        [JsonProperty("fx_requests")] public List<Dictionary<string, object>> FxRequests;
        [JsonProperty("repetition_penalty")] public int? RepetitionPenalty;
        [JsonProperty("deterministic_fallback")] public bool? DeterministicFallback;
    }

    // from selection.schema.json
    [Serializable]
    public class AssetSelectionRequest
    {
        [JsonProperty("schema_version")] public string SchemaVersion;
        [JsonProperty("kind")] public string Kind;
        [JsonProperty("biome")] public string Biome;
        [JsonProperty("theme")] public string Theme;
        [JsonProperty("tags")] public List<string> Tags;
        [JsonProperty("constraints")] public Dictionary<string, object> Constraints;
        [JsonProperty("allow_ai_generation")] public bool? AllowAiGeneration;
    }
}
